# Generated by Django 4.0.6 on 2022-07-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polles', to='interview.poll', verbose_name='Опрос')),
                ('variantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='interview.choice', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответ',
                'db_table': 'answering',
            },
        ),
    ]
